# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Clone and install circom
      uses: actions/checkout@v2
      with:
        repository: iden3/circom
        path: circom
        ref: master
    - name: Install latest rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          **/target
          ~/.cargo
        key: sha512-0.0.1  
    - run: cargo build --release --manifest-path=circom/Cargo.toml && cargo install --path circom/circom    
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
